### ISSUE TITLE
Feature request: Add schedule restart

### ISSUE THREAD

**Issue by fnovoac** [UbhiTS/ad-autointernetrebooter#3]
Hi, awesome project. Thank you for this and the others projects. I just want to know if you could add the ability to schedule a rest based on day an hour.

**Comment by UbhiTS** [comment]
sure, I can do that ... are you still using the integration? ... I've been away for about a year but back now. Also, recently I've been having some issues with the speedtest integration. is this working for you ?

**Comment by UbhiTS** [comment]
closing issue due to no response
